### ISSUE TITLE
Is is possible to switch through diagnostic messages in statusline by timer?

### ISSUE THREAD

**Issue by cpkio** [Isrothy/lualine-diagnostic-message#3]
What do you think?

**Comment by Isrothy** [comment]
I'm not sure about the use of this feature. If there are many diagnostic messages on one line, `vim.diagnostic.open_float` should be the right place to show message. Besides, switching by time may not be a good idea because switching the message before read through is annoying. If you want to manually control when to switch, why not just show them in a float window?

**Comment by cpkio** [comment]
I've thought about this and you're right: showing a float on idle timeout is a better solution.
